/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Dashboard: typeof import('./components/Dashboard.vue')['default']
    DialogBase: typeof import('./components/DialogBase.vue')['default']
    FileUploadDialog: typeof import('./components/FileUploadDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransactionAddForm: typeof import('./components/TransactionAddForm.vue')['default']
  }
}
