/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountAddEditForm: typeof import('./components/AccountAddEditForm.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CashflowCard: typeof import('./components/CashflowCard.vue')['default']
    CategoryAddEditForm: typeof import('./components/CategoryAddEditForm.vue')['default']
    Dashboard: typeof import('./components/Dashboard.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    DialogBase: typeof import('./components/DialogBase.vue')['default']
    FileUploadDialog: typeof import('./components/FileUploadDialog.vue')['default']
    ImportedFiles: typeof import('./components/ImportedFiles.vue')['default']
    MerchantAddEditForm: typeof import('./components/MerchantAddEditForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsManagement: typeof import('./components/SettingsManagement.vue')['default']
    SettingsManagementAccount: typeof import('./components/SettingsManagementAccount.vue')['default']
    SettingsManagementCategory: typeof import('./components/SettingsManagementCategory.vue')['default']
    SettingsManagementMerchants: typeof import('./components/SettingsManagementMerchants.vue')['default']
    TagsContainer: typeof import('./components/TagsContainer.vue')['default']
    TransactionAddForm: typeof import('./components/TransactionAddForm.vue')['default']
    TransactionQuickFindDialog: typeof import('./components/TransactionQuickFindDialog.vue')['default']
    TransactionsListItem: typeof import('./components/TransactionsListItem.vue')['default']
  }
}
